//
// Automatically generated make config: don't edit
// Enoch Configuration
// Thu Jul  9 12:44:01 2026
// 
#define CONFIG_IS_BUILTIN   1
#define CONFIG_IS_MODULE    2
#define CONFIG_UCLIBCXX_MODULE CONFIG_IS_MODULE
#define CONFIG_SATA_MODULE CONFIG_IS_MODULE
#define CONFIG_KLIBC_MODULE CONFIG_IS_MODULE
#define CONFIG_BOOT1_HFS_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS CONFIG_IS_BUILTIN
#define CONFIG_MODULES CONFIG_IS_BUILTIN
#define CONFIG_BOOT0_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_ACPICODEC_MODULE CONFIG_IS_MODULE
#define CONFIG_OPTIMIZATION_LEVEL "-Os"
#define CONFIG_KERNELPATCHER_MODULE CONFIG_IS_BUILTIN
#define CONFIG_BDMESG CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE_VERBOSE CONFIG_IS_BUILTIN
#define CONFIG_SECTORSIZE CONFIG_IS_BUILTIN
#define CONFIG_BOOT1INSTALL CONFIG_IS_BUILTIN
#define CONFIG_BOOT1_HFS_ACTIVE CONFIG_IS_BUILTIN
#define CONFIG_FILENVRAM_MODULE CONFIG_IS_BUILTIN
#define CONFIG_FDISK440 CONFIG_IS_BUILTIN
#define CONFIG_RESOLUTION_MODULE CONFIG_IS_MODULE
#define CONFIG_KEYLAYOUT_MODULE CONFIG_IS_MODULE
