name: Chameleon

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    name: Chameleon
    runs-on: macOS-10.13
    steps:
      - uses: actions/checkout@v6

      - name: Manage Version
        run: |
          git fetch --prune --unshallow --tags
          echo "CUR_TAG=$(git tag -l | tail -1)" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Build Chameleon
        run: |
          chmod +x ./Makefile
          
      - name: Prepare Release
        run: |
          make
          (cd "sym/" || exit 1)
          releaseItems=(build/Release)
          for releaseItem in "${releaseItems[@]}"; do cp -Rf "${releaseItem}" ./ || exit 1; done

      - name: 'Tar files'
        run: tar -cvf ./sym/i386.tar ./sym/i386

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Chameleon-${{ env.GIT_SHA }}
          path: |
            sym/i386.tar
